### ISSUE TITLE
where I find the patches ? 

### ISSUE THREAD

**Issue by sergiomb2** [rpmsphere/spec#3]
https://github.com/rpmsphere/spec/blob/master/h/hardinfo.spec#L10 where I can download  build-fix.diff without download all src.rpm ? 

Thank you 

BTW : I updated hardinfo package here 

https://copr-dist-git.fedorainfracloud.org/cgit/sergiomb/clonezilla/hardinfo.git/tree/?id=c6f7634250bbe3f3067c86f3122580941ecc4ddf

https://copr.fedorainfracloud.org/coprs/sergiomb/clonezilla/package/hardinfo/

**Comment by bluebat** [comment]
no other place.

**Comment by sergiomb2** [comment]
ok, thank you for the information
